require "parallel"
require "thread_safe"
require "securerandom"

RUBY_SRC = "ruby-src"
RUBY_DIR = "ruby-src-macroize"
RUBY_FAIL_LOG = "ruby-failure.log"

N = Parallel.processor_count

def paths(name)
  { :src         => "#{name}-src",
    :dir         => "#{name}-src-macroize",
    :failure_log => "#{name}-failure.log",
    :info_log    => "#{name}-info.log" }
end

def define_grub(name, &block)
  task "do_#{name}_grub" do
    block.call(name) unless File.directory? paths(name)[:src]
    sh "rm -rf #{paths(name)[:dir]}" if File.directory? paths(name)[:dir]
    sh "cp -r #{paths(name)[:src]} #{paths(name)[:dir]}"
  end
end

def define_pre(name, &block)
  task "do_#{name}_pre" do
    Dir.chdir(paths(name)[:dir]) do
      block.call(name)
    end
  end
end

def define_post(name, &block)
  task "do_#{name}_post" do
    Dir.chdir(paths(name)[:dir]) do
      block.call(name)
    end
  end
end

def define_tests_for(name, cpp_opts)
  failures = []
  if File.exists? paths(name)[:failure_log]
    File.open(paths(name)[:failure_log]).each do |line|
      failures << line.chomp
    end
  end

  Dir.chdir(paths(name)[:dir]) do
    testno = 0
    Dir.glob("./**/*.c") do |f|
      fail_mark = (failures.include? f) ? "[fail]" : ""
      testno += 1
      desc "#{fail_mark} (#{f})"
      task "#{name}#{testno}" do
        Dir.chdir(paths(name)[:dir]) do
          sh "cp #{File.join("../#{paths(name)[:src]}", f)} #{f}"
          sh "macro-of-inline #{f} #{cpp_opts} --record ../record-macro-of-inline"
        end
      end
    end
  end if File.directory? paths(name)[:dir]
end

# options
# ignore :: []
def define_test_for(name, cpp_opts, options = {})
  ignore_cfiles = options.fetch(:ignore, [])

  task "do_#{name}" do
    Dir.chdir(paths(name)[:dir]) do
      cfiles = []
      Dir.glob("./**/*.c") do |f|
        cfiles << f
      end
      cfiles.delete_if { |e| ignore_cfiles.include? e }

      success_list = ThreadSafe::Array.new
      failure_list = ThreadSafe::Array.new

      # ignore files are granted as failure
      failure_list += ignore_cfiles

      Parallel.each(cfiles, in_threads: N) do |f|
        # Looked at the Makefile
        tmpfile = "/tmp/#{SecureRandom.random_number(10**32)}.c"
        `macro-of-inline #{f} #{cpp_opts} -o #{tmpfile}`
        e = $?.exitstatus
        if e == 0
          success_list << f
          `cp #{tmpfile} #{f}`
        else
          failure_list << f
          puts "[macroize] failed: #{f}"
        end
        `rm -r #{tmpfile}`
      end

      perc = success_list.size.to_f / (success_list.size + failure_list.size)
      File.open("../#{paths(name)[:info_log]}", "w") do |f|
        f.write """\
success: #{perc}%
"""
      end

      File.open("../#{paths(name)[:failure_log]}", "w") do |f|
        f.write """\
#{failure_list.join("\n")}
"""
      end
    end
  end

  desc "test with #{name} source tree"
  task name => ["do_#{name}_grub", "do_#{name}_pre", "do_#{name}", "do_#{name}_post"]

  define_tests_for(name, cpp_opts)
end

RUBY_CPP_OPTS = "-X _DRUBY_EXPORT _I.ext/include/x86_64-linux _I./include _I. --with-cpp=gcc --fake-include=../ruby_fake_include.h"
# FIXME
# Some files are not found in the source tree. Some of them are generated before compilation.
# We need to add code into the "pre" hook to generate them. Mark (OK) if you add ones.
RUBY_IGNORE = [
  "./regcomp.c", # Not preprocessed properly because too big?
  "./main.c",
  "./vsnprintf.c",
  "./dln_find.c",
  "./missing/nextafter.c",
  "./vm_insnhelper.c",
  "./vm_exec.c",
  "./vm_method.c",
  "./vm_eval.c",
  "./siphash.c",
  "./thread_win32.c",
  "./thread_pthread.c",
  "./dln.c",
  "./id.c", # not found (OK)
  "./eval_error.c",
  "./eval_jump.c",
  "./eventids1.c", # not found
  "./eventids2.c", # not found
  "./lex.c", # not found (OK)
  "./ext/socket/constdefs.c", # not found
  "./ext/nkf/nkf-utf8/utf8tbl.c",
  "./ext/nkf/nkf-utf8/nkf.c",
  "./ext/nkf/nkf-utf8/nkf32dll.c", # not found
  "./ext/ripper/eventids2table.c", # not found
  "./enc/shift_jis.c",
]
define_grub("ruby") do |name|
  sh "git clone https://github.com/ruby/ruby #{paths(name)[:src]}"
end
define_pre("ruby") do
  sh "autoconf && ./configure"
  sh "make id.h"
  sh "make id.c"
  sh "make lex.c"
  sh "make probes.h"
end
define_post("ruby") do
  sh "./configure && make -j #{N} && make test"
end
define_test_for("ruby", RUBY_CPP_OPTS, :ignore => RUBY_IGNORE)

FIO_CPP_OPTS = "-X _D_LARGEFILE_SOURCE _D_FILE_OFFSET_BITS=64 _DFIO_INTERNAL _D_FORTIFY_SOURCE_2 _DFIO_INC_DEBUG --with-cpp=gcc --fake-include=../fio_fake_include.h"
define_grub("fio") do |name|
  sh "git clone git://git.kernel.dk/fio.git #{paths(name)[:src]}"
end
define_pre("fio") do
  sh "./configure"
end
define_post("fio") do
  sh "./configure && make"
end
define_test_for("fio", FIO_CPP_OPTS)

PYTHON_CPP_OPTS = "-X _DNDEBUG _I. _IInclude _I./Include --with-cpp=gcc --fake-include=../python_fake_include.h"
PYTHON_IGNORE = [
  "./Parser/parsetok.c",
  "./Parser/tokenizer.c",
  "./Modules/expat/xmltok_impl.c",
  "./Modules/expat/xmltok_ns.c",
  "./Modules/_ctypes/libffi/src/dlmalloc.c",
  "./Modules/getaddrinfo.c",
  "./Modules/getnameinfo.c",
]
define_grub("python") do |name|
  sh "hg clone https://hg.python.org/cpython #{paths(name)[:src]}"
end
define_pre("python") do
  sh "./configure"
end
define_post("python") do
  sh "./configure && make -j #{N} && make test"
end
define_test_for("python", PYTHON_CPP_OPTS, :ignore => PYTHON_IGNORE)
